---
control:
  hosts:
    local-control:
      ansible_connection: local
    control-vm:
      ansible_host: # Control vm public IP
      ansible_user: azureuser
      ansible_ssh_private_key_file: # Private key path

dbservers:
  hosts:
    appserver-vm:
    dbserver-vm:
      ansible_host: # DB vm ip
      ansible_user: azureuser
      ansible_ssh_private_key_file: # Private key path

appservers:
  hosts:
      ansible_host: # App vm ip
      ansible_user: azureuser
      ansible_ssh_private_key_file: 