---
# control:
#   hosts:
#     local-control:
#       ansible_connection: local
#     control-vm:
#       ansible_host: # Control vm public IP
#       ansible_user: azureuser
#       ansible_ssh_private_key_file: # Private key path

dbservers:
  hosts:
    dbserver-vm:
      ansible_host: 192.168.56.10
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/ansible/vagrant-db/.vagrant/machines/default/virtualbox/private_key

appservers:
  hosts:
    appserver-vm: 
      ansible_host: 192.168.56.11
      ansible_user: vagrant
      ansible_ssh_private_key_file:   ~/ansible/vagrant-b-f/.vagrant/machines/default/virtualbox/private_key
    k8s-vm:
      ansible_host: 192.168.56.13
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/ansible/vagrant-k8s/.vagrant/machines/k8s-vm/virtualbox/private_key


dockerservers: 
  hosts: 
    docker-vm:
      ansible_host: 192.168.56.12
      ansible_user: vagrant
      ansible_ssh_private_key_file: ~/ansible/vagrant-docker-vm/.vagrant/machines/default/virtualbox/private_key