Vagrant.configure("2") do |config|
  config.vm.define "k8s-vm" do |k8s|
    k8s.vm.box = "ubuntu/jammy64"
    k8s.vm.hostname = "k8s-vm"
    k8s.vm.network "private_network", ip: "192.168.56.13"

    # Resources
    k8s.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"  # 4 GB RAM
      vb.cpus = 2         # 2 CPU cores
    end
  end
end
